import {
  Box,
  Button,
  Card,
  Grid,
  Heading,
  List,
  Stack,
  Text,
  VStack,
} from "@chakra-ui/react";
import { useLogin } from "../context/auth-context";
import { Quotas } from "../components/quotas";
import { TRANSCRIBE_QUOTAS } from "model";
import { formatDuration } from "date-fns";
import { ExternalLink } from "@/components/externalLink";
import { NextPageWithLayout } from "@/pages/_app";
import { LoginLayout } from "../layout/layout";

const Login: NextPageWithLayout = () => {
  const styles = {
    root: {
      bgColor: { base: "gray.100", _dark: "gray.700" },
    },
  };

  const { handleLogin } = useLogin();
  return (
    <Stack align={"start"} gap={{ base: 4, lg: 10 }}>
      <Card.Root
        variant={"outline"}
        size={"sm"}
        width={{ base: "100%", lg: "unset" }}
        css={styles.root}
      >
        <Card.Header>
          <Card.Title asChild>
            <Heading as={"h1"} fontSize={"4xl"} lineHeight={1} pb={4}>
              QUT audio transcription service
            </Heading>
          </Card.Title>
        </Card.Header>
        <Card.Body>Please log in to access this service.</Card.Body>
        <Card.Footer>
          <Button colorPalette={"blue"} variant={"solid"} onClick={handleLogin}>
            Log in
          </Button>
        </Card.Footer>
      </Card.Root>
      <Grid
        templateColumns={{ base: undefined, lg: "repeat(3, 1fr)" }}
        gap={4}
        pb={20}
      >
        <Card.Root size={"sm"} variant={"outline"} css={styles.root}>
          <Card.Header>
            <Card.Title asChild>
              <Heading as={"h2"} fontSize={"xl"}>
                About QUT Transcribe
              </Heading>
            </Card.Title>
          </Card.Header>
          <Card.Body>
            <VStack gap={4}>
              <Text>
                This service is powered by{" "}
                <ExternalLink href={"https://aws.amazon.com/transcribe/"}>
                  Amazon Transcribe
                </ExternalLink>
                . Amazon transcribe uses a deep learning process called
                automatic speech recognition (ASR) to convert speech to text
                quickly and accurately. It can be used to transcribe audio and
                video files, and includes speaker identification. Amazon
                Transcribe is powered by a next-generation, multi-billion
                parameter speech foundation model that delivers high accuracy
                transcriptions for streaming and recorded speech.
              </Text>
              <Text>
                Transcription summaries are generated by{" "}
                <ExternalLink href={"https://aws.amazon.com/bedrock/"}>
                  Amazon Bedrock
                </ExternalLink>
                using{" "}
                <ExternalLink href={"https://www.anthropic.com/claude/haiku"}>
                  Anthropic&apos;s Claude Haiku
                </ExternalLink>{" "}
                model. By using this service you are expected to comply with{" "}
                <ExternalLink href={"https://www.anthropic.com/legal/aup"}>
                  Anthropic&apos;s Usage Policy.
                </ExternalLink>
              </Text>
            </VStack>
          </Card.Body>
        </Card.Root>
        <Card.Root size={"sm"} variant={"outline"} css={styles.root}>
          <Card.Header>
            <Card.Title asChild>
              <Heading as={"h2"} fontSize={"xl"}>
                Storage and security
              </Heading>
            </Card.Title>
          </Card.Header>
          <Card.Body>
            <VStack gap={4}>
              <Box>
                Uploaded media and generated transcriptions are:
                <List.Root listStylePosition={"inside"}>
                  <List.Item>
                    Stored in the Amazon Web Services (AWS) Sydney region
                  </List.Item>
                  <List.Item>
                    Kept for {formatDuration(TRANSCRIBE_QUOTAS.storageDuration)}{" "}
                    and then automatically deleted
                  </List.Item>
                  <List.Item>Encrypted in transit and at rest</List.Item>
                  <List.Item>
                    Media and transcriptions are accessible only by the uploader
                  </List.Item>
                  <List.Item>
                    For more information refer to the:{" "}
                    <ExternalLink
                      href={
                        "https://docs.aws.amazon.com/transcribe/latest/dg/security.html"
                      }
                    >
                      Amazon Transcribe Security Documentation{" "}
                    </ExternalLink>
                    .
                  </List.Item>
                </List.Root>
              </Box>
              <Box>
                Generated transcription summaries:
                <List.Root listStylePosition={"inside"}>
                  <List.Item>
                    Does not use your prompts and completions to train any AWS
                    models and does not distribute them to third parties.
                  </List.Item>
                  <List.Item>
                    Uses classifier metrics identify potential violations of{" "}
                    <ExternalLink href={"https://aws.amazon.com/aup/"}>
                      Acceptable Use
                    </ExternalLink>{" "}
                    and{" "}
                    <ExternalLink
                      href={"https://aws.amazon.com/ai/responsible-ai/policy/"}
                    >
                      Responsible Use
                    </ExternalLink>{" "}
                    policies.
                  </List.Item>
                </List.Root>
              </Box>
            </VStack>
          </Card.Body>
        </Card.Root>
        <Card.Root size={"sm"} variant={"outline"} css={styles.root}>
          <Card.Header>
            <Card.Title asChild>
              <Heading as={"h2"} fontSize={"xl"}>
                Quotas and limits
              </Heading>
            </Card.Title>
          </Card.Header>
          <Card.Body>
            <Quotas
              {...TRANSCRIBE_QUOTAS}
              supportedFileFormats={[
                "wav",
                "flac",
                "amr",
                "3ga",
                "mp3",
                "mp4",
                "m4a",
                "oga",
                "ogg",
                "opus",
              ]}
            />
          </Card.Body>
        </Card.Root>
      </Grid>
    </Stack>
  );
};

export const getStaticProps = () => {
  return {
    props: {
      isLanding: true,
    },
  };
};

Login.getLayout = (page) => {
  return <LoginLayout isLanding={true}>{page}</LoginLayout>;
};

export default Login;
