import {
  Box,
  Button,
  Card,
  Grid,
  Heading,
  List,
  Stack,
  Text,
  VStack,
} from "@chakra-ui/react";
import { Quotas } from "../components/quotas";
import { TRANSCRIBE_QUOTAS } from "model";
import { formatDuration } from "date-fns";
import { ExternalLink } from "@/components/externalLink";
import { handleLogin, NextPageWithLayout } from "@/pages/_app";
import Layout from "../layout/layout";
import { useAuth } from "../context/auth-context";
import { useRouter } from "next/router";

const Login: NextPageWithLayout = () => {
  const { authenticated } = useAuth();
  const router = useRouter();

  const styles = {
    root: {
      bgColor: { base: "gray.100", _dark: "gray.700" },
    },
  };

  if (authenticated) {
    router.push("/").then(() => console.log("Logged in routing to home."));
  }

  return (
    <Stack align={"start"} gap={{ base: 4, lg: 10 }}>
      <Card.Root
        variant={"outline"}
        size={"sm"}
        width={{ base: "100%", lg: "unset" }}
        css={styles.root}
      >
        <Card.Header>
          <Card.Title asChild>
            <Heading as={"h1"} fontSize={"4xl"} lineHeight={1} pb={4}>
              QUT Transcription Service
            </Heading>
          </Card.Title>
        </Card.Header>
        <Card.Body>Please log in to access this service.</Card.Body>
        <Card.Footer>
          <Button colorPalette={"blue"} variant={"solid"} onClick={handleLogin}>
            Log in
          </Button>
        </Card.Footer>
      </Card.Root>
      <Grid
        templateColumns={{ base: undefined, lg: "repeat(3, 1fr)" }}
        gap={4}
        pb={20}
      >
        <Card.Root size={"sm"} variant={"outline"} css={styles.root}>
          <Card.Header>
            <Card.Title asChild>
              <Heading as={"h2"} fontSize={"xl"}>
                About QUT Transcribe
              </Heading>
            </Card.Title>
          </Card.Header>
          <Card.Body>
            <VStack gap={4}>
              <Box>
                <Heading as={"h3"} fontSize={"md"} pb={1}>
                  Transcription
                </Heading>
                <Text>
                  This service is powered by{" "}
                  <ExternalLink href={"https://aws.amazon.com/transcribe/"}>
                    Amazon Transcribe
                  </ExternalLink>
                  . Amazon transcribe uses a deep learning process called
                  automatic speech recognition (ASR) to convert speech to text
                  quickly and accurately. It can be used to transcribe audio and
                  video files, and includes speaker identification. Amazon
                  Transcribe is powered by a next-generation, multi-billion
                  parameter speech foundation model that delivers high accuracy
                  transcriptions for streaming and recorded speech.
                </Text>
              </Box>
              <Box>
                <Heading as={"h3"} fontSize={"md"} pb={1}>
                  Translation
                </Heading>
                <Text>
                  Once your media is transcribed, you can have the transcript
                  automatically translated into another language using{" "}
                  <ExternalLink href={"https://aws.amazon.com/translate/"}>
                    Amazon Translate
                  </ExternalLink>{" "}
                  and download it as subtitles, a document, or plain text.
                  Translation happens after transcription, so it takes a little
                  longer. Machine translations aren&apos;t always perfect, so
                  it&apos;s worth reviewing them before relying on them.
                </Text>
              </Box>
              <Box>
                <Heading as={"h3"} fontSize={"md"} pb={1}>
                  PII redaction
                </Heading>
                <Text>
                  Personally Identifiable Information (PII) is information that
                  could identify someone, such as names, addresses, phone
                  numbers, and credit card details. When PII redaction is turned
                  on, any PII we detect is hidden in the transcription. This
                  option is available for English (US) transcriptions.
                </Text>
              </Box>
              <Box>
                <Heading as={"h3"} fontSize={"md"} pb={1}>
                  Summaries
                </Heading>
                <Text>
                  Transcription summaries are generated by{" "}
                  <ExternalLink href={"https://aws.amazon.com/bedrock/"}>
                    Amazon Bedrock
                  </ExternalLink>
                  using{" "}
                  <ExternalLink href={"https://www.anthropic.com/claude/haiku"}>
                    Anthropic&apos;s Claude Haiku
                  </ExternalLink>{" "}
                  model. By using this service you are expected to comply with{" "}
                  <ExternalLink href={"https://www.anthropic.com/legal/aup"}>
                    Anthropic&apos;s Usage Policy.
                  </ExternalLink>
                </Text>
              </Box>
            </VStack>
          </Card.Body>
        </Card.Root>
        <Card.Root size={"sm"} variant={"outline"} css={styles.root}>
          <Card.Header>
            <Card.Title asChild>
              <Heading as={"h2"} fontSize={"xl"}>
                Storage and security
              </Heading>
            </Card.Title>
          </Card.Header>
          <Card.Body>
            <VStack gap={4}>
              <Box>
                Uploaded media, generated transcriptions, and generated
                translations are:
                <List.Root listStylePosition={"inside"}>
                  <List.Item>
                    Stored in the Amazon Web Services (AWS) Sydney region
                  </List.Item>
                  <List.Item>
                    Kept for {formatDuration(TRANSCRIBE_QUOTAS.storageDuration)}{" "}
                    and then automatically deleted
                  </List.Item>
                  <List.Item>Encrypted in transit and at rest</List.Item>
                  <List.Item>Only accessible by the uploader</List.Item>
                  <List.Item>
                    For more information refer to the{" "}
                    <ExternalLink
                      href={
                        "https://docs.aws.amazon.com/transcribe/latest/dg/security.html"
                      }
                    >
                      Amazon Transcribe Security Documentation
                    </ExternalLink>{" "}
                    and the{" "}
                    <ExternalLink
                      href={
                        "https://docs.aws.amazon.com/translate/latest/dg/security.html"
                      }
                    >
                      Amazon Translate Security Documentation
                    </ExternalLink>
                    .
                  </List.Item>
                </List.Root>
              </Box>
              <Box>
                Generated transcription summaries:
                <List.Root listStylePosition={"inside"}>
                  <List.Item>
                    Do not use your prompts and completions to train any AWS
                    models, and are not distributed to third parties.
                  </List.Item>
                  <List.Item>
                    Use classifier metrics to identify potential violations of{" "}
                    <ExternalLink href={"https://aws.amazon.com/aup/"}>
                      Acceptable Use
                    </ExternalLink>{" "}
                    and{" "}
                    <ExternalLink
                      href={"https://aws.amazon.com/ai/responsible-ai/policy/"}
                    >
                      Responsible Use
                    </ExternalLink>{" "}
                    policies.
                  </List.Item>
                  <List.Item>
                    For more information refer to the{" "}
                    <ExternalLink
                      href={
                        "https://docs.aws.amazon.com/bedrock/latest/userguide/security.html"
                      }
                    >
                      Amazon Bedrock Security Documentation
                    </ExternalLink>
                    .
                  </List.Item>
                </List.Root>
              </Box>
            </VStack>
          </Card.Body>
        </Card.Root>
        <Card.Root size={"sm"} variant={"outline"} css={styles.root}>
          <Card.Header>
            <Card.Title asChild>
              <Heading as={"h2"} fontSize={"xl"}>
                Quotas and limits
              </Heading>
            </Card.Title>
          </Card.Header>
          <Card.Body>
            <Quotas
              {...TRANSCRIBE_QUOTAS}
              supportedFileFormats={[
                "wav",
                "flac",
                "amr",
                "3ga",
                "mp3",
                "mp4",
                "m4a",
                "oga",
                "ogg",
                "opus",
              ]}
            />
          </Card.Body>
        </Card.Root>
      </Grid>
    </Stack>
  );
};

Login.getLayout = (page) => {
  return (
    <Layout isLanding={true} isAuthenticated={false} onLogin={handleLogin}>
      {page}
    </Layout>
  );
};

export default Login;
