name: Build
on:
  push:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Linting
        run: pnpm lint
      - name: Formatting
        run: pnpm fmt:check
      - name: Build modules
        run: pnpm build
      - name: Run tests
        run: pnpm test
